#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Raghuveer Dendukuri
# Author: Raghuveer Dendukuri · Co-author: Claude Code (Opus)
"""Generate a side-by-side comparison page for one use case.

The repo's whole thesis is that the four approaches differ. Until now a reader
had to open four folders and diff them mentally. This renders the comparison:
the *same* problem, the core of each implementation, how much code each costs,
and — when trace data is present — what each one measurably did at runtime.

Generated, not hand-written, so it cannot drift from the code it describes.

    python scripts/compare_usecase.py 08-autonomous-react
    python scripts/compare_usecase.py --all --check     # CI-style drift check
"""
from __future__ import annotations

import argparse
import ast
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
APPROACHES = ("raw-api", "langchain", "langgraph", "claude-agent-sdk")
OUT_DIR = REPO / "docs" / "compare"
DATA_DIR = OUT_DIR / "data"

# Where the heart of each implementation lives: (module, symbol). Chosen so the
# rendered snippets answer the same question — "what drives the loop?" — rather
# than showing whatever happens to be at the top of a file.
MANIFEST: dict[str, dict[str, tuple[str, str]]] = {
    "08-autonomous-react": {
        "raw-api": ("app/react.py", "run_react"),
        "langchain": ("app/react.py", "run_react"),
        "langgraph": ("app/react.py", "build_react_graph"),
        "claude-agent-sdk": ("app/react_agent.py", "run_react"),
    },
}

# One line per approach: the claim the code below is evidence for.
TAKE: dict[str, str] = {
    "raw-api": "You write the loop, the parser, and the stop condition.",
    "langchain": "The framework supplies tools and message types; the loop is still yours.",
    "langgraph": "The loop becomes a graph: nodes, a conditional edge, and a cycle.",
    "claude-agent-sdk": "There is no loop in the repo. The SDK owns it.",
}


def code_lines(path: Path) -> int:
    """Non-blank, non-comment lines — a fairer size measure than raw wc -l."""
    total = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            total += 1
    return total


def app_size(project: Path) -> int:
    return sum(code_lines(p) for p in sorted((project / "app").glob("*.py")))


def extract(project: Path, module: str, symbol: str) -> str:
    """Return the source of ``symbol`` from ``module``.

    Uses the AST rather than regex or line markers, so the sources stay clean
    and a rename fails loudly here instead of silently rendering the wrong code.
    """
    path = project / module
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if node.name == symbol:
                segment = ast.get_source_segment(source, node)
                if segment:
                    return segment
    raise SystemExit(f"{path}: no top-level symbol named {symbol!r}")


def render(usecase: str) -> str:
    entries = MANIFEST[usecase]
    lines: list[str] = []
    add = lines.append

    add(f"# {usecase} — the same problem, four ways")
    add("")
    add(
        "<!-- GENERATED by scripts/compare_usecase.py. Do not edit by hand; "
        "run the script. -->"
    )
    add("")
    add(
        "Every approach here solves an identical task with identical tools. What "
        "differs is how much of the machinery you write yourself — and, as the "
        "measured section below shows, what you can still see once it is running."
    )
    add("")

    # -- at a glance ------------------------------------------------------- #
    add("## At a glance")
    add("")
    add("| Approach | `app/` lines | Core symbol | The trade |")
    add("|---|---:|---|---|")
    for approach in APPROACHES:
        module, symbol = entries[approach]
        project = REPO / approach / usecase
        add(
            f"| [`{approach}`](../../{approach}/{usecase}) | {app_size(project)} "
            f"| `{module}::{symbol}` | {TAKE[approach]} |"
        )
    add("")
    add(
        "Line counts are non-blank, non-comment lines across `app/`, and include "
        "each project's settings, HTTP layer, and tools — not just the loop. They "
        "are a rough proxy for how much surface you own, not a scoreboard."
    )
    add("")

    # -- the code ---------------------------------------------------------- #
    add("## The core of each implementation")
    add("")
    for approach in APPROACHES:
        module, symbol = entries[approach]
        project = REPO / approach / usecase
        add(f"### {approach} — `{module}`")
        add("")
        add(f"> {TAKE[approach]}")
        add("")
        add("```python")
        add(extract(project, module, symbol))
        add("```")
        add("")

    # -- measured ---------------------------------------------------------- #
    data_path = DATA_DIR / f"{usecase}.json"
    if data_path.exists():
        data = json.loads(data_path.read_text(encoding="utf-8"))
        add("## Measured, from a real traced run")
        add("")
        add(
            f"Captured with `?trace=1` on {data['captured_at']} against "
            f"`{data['model']}`. Regenerate with "
            "`python scripts/trace_compare.py <usecase>`. Schema: "
            "[`docs/trace-format.md`](../trace-format.md)."
        )
        add("")
        add("| | " + " | ".join(f"`{a}`" for a in APPROACHES) + " |")
        add("|---|" + "---|" * len(APPROACHES))
        for label, key in (
            ("Model calls / turns", "steps"),
            ("Tool calls", "tool_calls"),
            ("Input tokens", "input_tokens"),
            ("Output tokens", "output_tokens"),
            ("Cost (USD)", "cost_usd"),
        ):
            cells = []
            for approach in APPROACHES:
                value = data["runs"].get(approach, {}).get(key)
                cells.append("not reported" if value is None else f"{value}")
            add(f"| {label} | " + " | ".join(cells) + " |")
        add("")
        for note in data.get("notes", []):
            add(f"- {note}")
        add("")

    add("## Read next")
    add("")
    add(
        "- Each project's own README explains its approach-specific decisions.\n"
        "- [`docs/trace-format.md`](../trace-format.md) — how these runs are "
        "recorded, and why the format is OpenTelemetry-shaped.\n"
        "- [`TRACKING.md`](../../TRACKING.md) — the per-use-case suitability "
        "matrix and every defect found by running these live."
    )
    add("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("usecase", nargs="?", help="e.g. 08-autonomous-react")
    parser.add_argument("--all", action="store_true", help="every manifested use case")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the generated page differs from what is committed",
    )
    args = parser.parse_args()

    if args.all:
        targets = sorted(MANIFEST)
    elif args.usecase:
        if args.usecase not in MANIFEST:
            raise SystemExit(
                f"no manifest entry for {args.usecase!r}; "
                f"known: {', '.join(sorted(MANIFEST))}"
            )
        targets = [args.usecase]
    else:
        parser.error("give a use case or --all")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    failed = False
    for usecase in targets:
        rendered = render(usecase)
        out = OUT_DIR / f"{usecase}.md"
        if args.check:
            current = out.read_text(encoding="utf-8") if out.exists() else ""
            if current != rendered:
                print(f"STALE  {out.relative_to(REPO)} — re-run this script")
                failed = True
            else:
                print(f"ok     {out.relative_to(REPO)}")
        else:
            out.write_text(rendered, encoding="utf-8", newline="\n")
            print(f"wrote  {out.relative_to(REPO)}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
